### ISSUE TITLE
When non-Error values are thrown they aren't be caught by `:default`

### ISSUE THREAD

**Issue by kanaka** [babashka/nbb#114]
**version**

0.1.0

**platform**

Ubuntu 20.04.3 with 16.10.0

**problem**

Normal ClojureScript (and JavaScript) can catch normal (non-Error) values when they are thrown, but nbb is not catching them.

**repro**

```clojure
user=> (try (throw (js/Error. "blah")) (catch :default e (prn :e e)))
:e #object[Error Error: blah]
user=> (try (throw "blah") (catch :default e (prn :e e)))
"blah"
```

**expected behavior**

Same as ClojureScript:

```clojure
cljs.user=> (try (throw (js/Error. "blah")) (catch :default e (prn :e e)))
:e #object[Error Error: blah]
cljs.user=> (try (throw "blah") (catch :default e (prn :e e)))
:e "blah"
```

Note that this is functionality supported natively by JavaScript itself:

```clojure
> try { throw("blah") } catch (e) { console.log("e:", e) }
e: blah
> try { throw([1,2,3]) } catch (e) { console.log("e:", e) }
e: [ 1, 2, 3 ]
```

**Comment by borkdude** [comment]
wat? I didn't know this was possible!

**Comment by kanaka** [comment]
Verified both this and #115. Thanks!

**Comment by borkdude** [comment]
@kanaka You're welcome. If you are using nbb at work or in an OSS project, it'd be great if you shared something about it here:

https://github.com/babashka/nbb/discussions/91
