### ISSUE TITLE
nbb does not launch on GraalVM's distribution of nodejs

### ISSUE THREAD

**Issue by littleli** [babashka/nbb#118]
I used the latest GraalVM (21.3.0) on MacOS (Big Sur)

After installing nodejs with `gu`:

```sh
$ gu install nodejs
```

I installed nbb and received this output, so it apears to be happy:

```sh
$ npm install -g nbb
/Users/alesnajmann/local/graalvm-ce-java17-21.3.0/Contents/Home/languages/nodejs/bin/nbb -> /Users/alesnajmann/local/graalvm-ce-java17-21.3.0/Contents/Home/languages/nodejs/lib/node_modules/nbb/out/nbb_main.js
+ nbb@0.1.1
updated 1 package in 2.253s
```

but after I try to run it it ends up with following error:

```sh
$ ./nbb 
----- Error --------------------------------------
Type:     TypeError
Message:  Invalid host defined options
Invalid host defined options
```

If there is a minimal possibility to make it work 🙏🏻 

I think there is a huge opportunity to direct interop between nodejs<->java interop using GraalVM, and so is for `nbb`.

**Comment by borkdude** [comment]
Oh wow, I didn't think of that use case yet. Thank you!

**Comment by borkdude** [comment]
@littleli It seems to be related to dynamic import.

This works though. So as long as you use only clojure core stuff and `js/...` it should work for now. I think nodejs on Graal might not have parity with the newest node.

```
$ $GRAALVM_HOME/bin/node out/nbb_main.js -e '(+ 1 2 3)'
6
```

**Comment by borkdude** [comment]
It seems the regular interop isn't working for nodejs on Graal

``` clojure
$ $GRAALVM_HOME/bin/node --jvm --polyglot out/nbb_main.js -e '(def bigint (js/Java.type "java.math.BigInteger")) (-> (.valueOf bigint 2))'
----- Error --------------------------------------
Type:     TypeError
Message:  invokeMember (apply) on java.lang.Class.valueOf failed due to: Message not supported.
invokeMember (apply) on java.lang.Class.valueOf failed due to: Message not supported.
```

But using `js/Reflect` it does work (I recently learned that this exists from @zane):

``` clojure
$ $GRAALVM_HOME/bin/node --jvm --polyglot out/nbb_main.js -e '(def bigint (js/Java.type "java.math.BigInteger")) (-> (js/Reflect.apply (.-valueOf bigint) nil #js [2]) str)'
"2"
```

Perhaps the interop in SCI should default to `Reflect` if it's available (not sure if it's supported everywhere).

**Comment by littleli** [comment]
Just for reference: https://github.com/oracle/graaljs/blob/master/docs/user/JavaScriptCompatibility.md

**Comment by borkdude** [comment]
A repro in pure JS:

```
> var x = BigInteger.valueOf.apply(BigInteger, [10])
Uncaught:
TypeError: invokeMember (apply) on java.lang.Class.valueOf failed due to: Message not supported.

> var x = Reflect.apply(BigInteger.valueOf, BigInteger, [10])
undefined
> x.toString()
'10'
```

**Comment by borkdude** [comment]
Btw, it seems now that `js/import` works on the newest GraalVM release (22.0.0.2):

``` clojure
$ GRAALVM_HOME/bin/node out/nbb_main.js -e '(ns foo (:require ["path" :as path])) (path/resolve "README.md")'
"/Users/borkdude/Dropbox/dev/clojure/nbb/README.md"
```

I have asked on the graalvm slack why the first example using `.apply` doesn't work, but I will ultimately fix it in nbb or SCI.

**Comment by borkdude** [comment]
Reply from Graal Slack:

Jan Štola  3 minutes ago
The first version assumes that BigInteger.valueOf has apply property. This is not true for Java functions (foreign/non-JavaScript executable objects) by default.

Jan Štola  < 1 minute ago
Reflect.apply is a generic request to call the the function/callable/executable. There is no need for a particular property in this case.

**Comment by borkdude** [comment]
Should be fixed in 0.1.4, releasing on CI

**Comment by borkdude** [comment]
https://twitter.com/borkdude/status/1487917339291041792

**Comment by borkdude** [comment]
Also got this response from the GraalVM slack:

```
FYI: --js.foreign-object-prototype puts Function.prototype on the prototype chain of foreign executables. In other words, the first test-case works with this option.
```
