### ISSUE TITLE
Consider allowing set! on any var for compatibility with CLJS

### ISSUE THREAD

**Issue by borkdude** [babashka/nbb#136]
```
(def x 1)
(set! x 2)
```

**Comment by borkdude** [comment]
The current way to do this is:

```
(alter-var-root! #'x (constantly 2))
```

**Comment by logseq-cldwalker** [comment]
I encountered this recently and `alter-var-root` worked as a workaround. The only downside is introducing a reader conditional for this

**Comment by logseq-cldwalker** [comment]
Confirm this works in latest nbb. Thanks!
