### ISSUE TITLE
Consider nbb.core/await for top level await

### ISSUE THREAD

**Issue by borkdude** [babashka/nbb#142]
Goal: 

- offer convenience of top-level async/await for REPL usage, without introducing complexity of async/await program transformation. 

``` clojure
(require '[nbb.core :refer [await]])
(def x (await ...))
```

would be the equivalent of:

``` javascript
const x = await ...
```

This would be convenient for REPL usage, e.g. when developing browser tests.

When defining a var and the contents of the var is an `AwaitPromise` type returned by `nbb.core/await`, we could await the contained promise and re-define the var with the resolved value. This would then also work for (statically) non-top-level stuff, as long as the returned value or var is wrapped with `nbb.core/await`:

``` clojure
(let [x (js/fetch ...)
  (await x))
```

``` clojure
(let [x (js/fetch ...)
  (def foo (await x)))
```

E.g. this would _not_ work:

``` clojure
(def x [(await (js/fetch ...))])
``` 

but this would:

``` clojure
(require '[promesa.core :as p])
(def x (await (p/let [x (js/fetch ...)]
                [x]))
```

## try/catch

How does this play with try/catch/finally? It doesn't, you should take care of error handling before returning the value.

``` clojure
(def x (await (p/catch (js/fetch ...) (fn [_] ..)))
```

**Comment by micahasmith** [comment]
why isn't good old promise dereference via @ a solution here?

**Comment by borkdude** [comment]
@micahasmith It doesn't work that way in CLJS/JS since you cannot block the current thread, like you can on the JVM. 

We _could_ extend IDeref to js/Promise and the implementation would do the same as `nbb.core/await`, such that

``` clojure
(def x (await (js/fetch ...)))
```
can be written as:

``` clojure
(def x @(js/fetch ...))
```

Wether we _should_, I don't know, perhaps people will not understand that the deref doesn't work everywhere like on the JVM.

**Comment by armincerf** [comment]
I think using @ will be misleading for people unfamiliar with javascript, like borkdude said, async doesn't work like the JVM does (unfortunately...). 

sticking as close to the same syntax as javascript seems sensible to me.

I definitely approve of this idea FWIW

**Comment by mauricioszabo** [comment]
BTW, `await` (in Node) is only available inside an async function, so for this to work correctly it may be needed to add some metadata/new `defn` syntax for the function to emit the right Node.JS code.

What I did do, in the past, was experiment with `deref` on promises with nbb: https://github.com/mauricioszabo/nbb/tree/deref-promises. This could allow for top-level `await` or `deref`, on the price of making the interpreter slightly slower (well, I did not optimize anything yet)

**Comment by borkdude** [comment]
> BTW, await (in Node) is only available inside an async function

This is no longer true in newer versions of Node.js.

**Comment by borkdude** [comment]
Thanks for sharing those patches. I don't want to make the interpreter any slower: just a convenience to define vars to promise results and "block" eval until the next line.

**Comment by mauricioszabo** [comment]
> This is no longer true in newer versions of Node.js.
On the REPL only, right? On actual scripts, it's still true at `v17.6.0` (just tested with a simple script):

```js
╰─>$ cat algo.js 
const a = await Promise.resolve(10)
```

```bash
╰─>$ node
Welcome to Node.js v17.6.0.
Type ".help" for more information.
> const a = await Promise.resolve(10)
undefined
> a
10
> 
╰─>$ vi algo.js

╰─>$ node algo.js 
/tmp/lol/algo.js:1
const a = await Promise.resolve(10)
          ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by borkdude** [comment]
Try `index.mjs`.

**Comment by mauricioszabo** [comment]
Better, but not perfect:

```
╰─>$ cat index.mjs 
function foo() {
  const a = await Promise.resolve(10)
  return a;
}

foo()

╰─>$ node index.mjs 
file:///tmp/lol/index.mjs:2
  const a = await Promise.resolve(10)
            ^^^^^

SyntaxError: Unexpected reserved word
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:115:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:293:14)
    at async link (node:internal/modules/esm/module_job:70:21)

Node.js v17.6.0
```

So `await` will still not work inside a function, unless we have a way to mark it as an async function in `nbb`.

**Comment by borkdude** [comment]
That's not what I'm after here. See title of issue: `Consider nbb.core/await for top level await`.

**Comment by borkdude** [comment]
I mainly want to add this to have some convenience while developing UI tests:

https://twitter.com/borkdude/status/1495819848320004108

**Comment by borkdude** [comment]
A small demo:

``` clojure
$ node out/nbb_main.js -e "
(require '[nbb.core :refer [await]] '[promesa.core :as p]) 
(def x (await (p/do (p/delay 1000) :result))) 
x"
:result
```

**Comment by borkdude** [comment]
In the REPL:
```
$ node out/nbb_main.js
Welcome to nbb v0.2.2!
user=> (require '[nbb.core :refer [await]] '[promesa.core :as p])
nil
user=> (def x (await (p/do (p/delay 1000) :result)))
#'user/x
user=> x
:result
```

**Comment by borkdude** [comment]
The movie:

![await](https://user-images.githubusercontent.com/284934/157291912-e613782d-75ec-49fd-a7ca-d5689ce7f3bb.gif)

**Comment by borkdude** [comment]
This all works:

```
(require '[promesa.core :as p])
(require '[nbb.core :refer [await]])
(prn :start)
(def x (await (p/do (p/delay 1000) :x-result)))
(prn :x x)
(def y (await (p/do (p/delay 1000) :y-result)))
(prn :y y)
(defn foo []
  (await (p/do (p/delay 1000) :foo-result)))
(def z (foo))
(prn [x y z])
```

```
:start
:x :x-result
:y :y-result
[:x-result :y-result :foo-result]
```

**Comment by borkdude** [comment]
This is the complete implementation (~10 lines): https://github.com/babashka/nbb/commit/cfc72dc51ea7cca331cbdd660001a5120d102456

**Comment by borkdude** [comment]
Publishing this as an experimental function in v0.2.3 now.
