### ISSUE TITLE
nbb nrepl-server crashes when attempting connect from emacs/cider running lispy

### ISSUE THREAD

**Issue by vxe** [babashka/nbb#145]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**
Node.js v17.4.0
Nbb version: 0.2.4

**platform**

MacOs Catalina 

emacs
```
    (add-hook 'cider-repl-mode-hook #'prettify-symbols-mode)
    (add-hook 'cider-repl-mode-hook #'lispy-mode)
```

**problem**

when connecting to a nbb nrepl-server process from emacs, where clojure-repl mode requires lispy, results in the following crash:

https://gist.github.com/vxe/c82b9d40bc3c4252e77c53f5bda5b1c5

**repro**

start nbb nrepl server
try and run `cider-connect-clj`

**expected behavior**

a repl connection should appear, the process should not immediately crash

**Comment by vxe** [comment]
Was able to fix by begrudgingly updating lispy from the emacs side, so technically this is user error.

I would think an error message that middleware "may not be configured properly" would be better than a crash but my opinion is pretty uninformed about rules of engagement between middleware and clj implementations 

Feel free to close if this sounds like a one off type issue

**Comment by borkdude** [comment]
Thanks. I will re-open this if more people respond to this with strong opinions :).
