### ISSUE TITLE
babashka.fs not available in nbb?

### ISSUE THREAD

**Issue by SimunKaracic** [babashka/nbb#151]
nbb version v0.2.9

OS: Mac OS Monterey v12.0.1

node version: v17.7.1

**When trying to use babashka.fs, I get the following error**
```
Message:  Could not find namespace: babashka.fs
Could not find namespace: babashka.fs
```

The following code works when run with `bb`, but fails with the above error when run with `nbb`
```
(require '[babashka.fs :as fs])
(fs/list-dir ".")
```

**Comment by borkdude** [comment]
Babashka fs is only available on the JVM for now.

**Comment by SimunKaracic** [comment]
Ah, alright, thanks!
