### ISSUE TITLE
Using cljs.test instead of clojure.test throws a traceback

### ISSUE THREAD

**Issue by chr15m** [babashka/nbb#158]
**version**

`0.3.2`

**platform**

Ubuntu GNU/Linux, Node v16.13.1.

**problem**

If `cljs.test` is required the following error is thrown by nbb:

```
----- Error --------------------------------------
Message:  No namespace: cljs.test
No namespace: cljs.test
```

If `clojure.test` is required instead it works fine.

**repro**

In a `.cljs` file require `cljs.test :refer-macros [is]`.

**expected behavior**

It should work the same as if `clojure.test` was required instead.

**Comment by borkdude** [comment]
With 0.3.2:

```
user=> (require '[cljs.test :as t])
nil
```

Are you sure you are using 0.3.2?

**Comment by borkdude** [comment]
Could you give a full standalone `.cljs` example here?

**Comment by chr15m** [comment]
Ok, I think I figured out a repro, let me know if it works for you:

```
mkdir repro
cd repro
echo {} > package.json
npm i nbb@latest github:chr15m/sitefox#a76e045b
# create hello.cljs (see below)
npx nbb --classpath ${NODE_PATH:=./node_modules}/sitefox/src/ hello.cljs
```

```clojure
(ns hello
  (:require
    [sitefox.ui :refer [log]]))

(log "hi")
```

**Comment by chr15m** [comment]
I am not sure if it's related but this also throws:

```
(ns hello
  (:require
    [cljs.test :refer-macros [is]]))

(defn hello
  {:test (fn [] (is true false))}
  []
  (print "hello"))

(hello)
```

The error message I see when running with nbb is slightly different:

```
----- Error --------------------------------------
Message:  Could not resolve symbol: is
Phase:    analysis
Could not resolve symbol: is
```

**Comment by borkdude** [comment]
That's a different error though? In nbb and also CLJS you can use `:refer [is]` but I'll support `:refer-macros` too, although that isn't strictly necessary for nbb.

**Comment by chr15m** [comment]
Yes the second one is a different error. The first error above was the one I mentioned in chat.

**Comment by borkdude** [comment]
Sorry for the confusion, I thought I was reading your first message because I clicked on that but then read your second message and skipped over the first

**Comment by borkdude** [comment]
Releasing as v0.3.3

**Comment by chr15m** [comment]
Tested my failing cases and it works now thanks!
