### ISSUE TITLE
caxa: Adding an NPM dependency causes standalone executable failure

### ISSUE THREAD

**Issue by pwhittin** [babashka/nbb#162]
nbb v0.3.3, caxa v2.1.0

Linux 5.4.0-107-generic Ubuntu SMP x86_64 GNU/Linux, Node v17.3.0

The caxa exampe found here:

https://github.com/babashka/nbb/blob/main/doc/caxa/README.md

works fine, but when I add an NPM dependency the created executable will only execute from within the development directory.  When I move it to some other directory, like my `bin` directory, it fails to execute because it cannot find the NPM dependency.

This repository:

https://github.com/pwhittin/nbb-npm-caxa

contains an example program that reproduces the problem.

The expected behavior is that the created executable will execute properly outside of the development directory.

**Comment by borkdude** [comment]
I adapted the caxa example so that it will work with bundled node_modules.

https://github.com/babashka/nbb/commit/3a36e116918f5d16a2a15b8c7675c98f8e6de5ee
