### ISSUE TITLE
Use medley as a dependency

### ISSUE THREAD

**Issue by logseq-cldwalker** [babashka/nbb#166]
**Is your feature request related to a problem? Please describe.**
I'm curious about using https://github.com/weavejester/medley/blob/master/src/medley/core.cljc as a normal dependency. I tried requiring it in using the documented write-deps bb task but encountered some cljs internals that nbb doesn't have. Specifically the missing classes and properties are cljs.core/IEditableCollection , PersistentQueue.*, MapEntry, UUID

**Describe the solution you'd like**
Could be handy to have medley run as a normal dependency

**Describe alternatives you've considered**
For now I can pull it in as a feature or just re-implement some of the fns we use from it

**Additional context**

I tried adding the `sci/init call with:
```clojure
 'cljs.core {'IEditableCollection (sci/copy-var IEditableCollection nbb-ns)
                                   'MapEntry (sci/copy-var MapEntry nbb-ns)
                                   'UUID (sci/copy-var UUID nbb-ns)
                                   'PersistentQueue (sci/copy-var PersistentQueue nbb-ns)
                                   ; 'PersistentQueue.EMPTY (sci/copy-var PersistentQueue.EMPTY nbb-ns)
                                   }
```
but this fails for PersistentQueue.EMPTY. The others seemed to load correctly

~~This library also makes use of `persistent!` and `transient` which I don't know if nbb supports. At least `(persistent!)` fails with `No protocol method ITransientCollection`~~ Nm. Glad to see these fns are supported

**Comment by borkdude** [comment]
`persistent!` and `transient` are supported:

```
$ nbb
Welcome to nbb v0.3.7!
user=> (persistent! (transient []))
[]
```

Let's focus on one snippet of code from medley at a time and then try to make that work.

**Comment by logseq-cldwalker** [comment]
Ah. Glad to see this work out of the box. Any thoughts on how PersistentQueue.EMPTY would be implemented? I think it's the only property preventing the ns from being loaded by nbb. I was hoping to load the ns and then see which tests fail

**Comment by borkdude** [comment]
Similar to:

```
$ nbb
Welcome to nbb v0.3.7!
user=> (def x #js {:a 1})
#'user/x
user=> x.a
"#error {:message \"Could not resolve symbol: x.a\", :data {:type :sci/error, :line 1, :column 1, :file nil, :phase \"analysis\"}}"
```

**Comment by logseq-cldwalker** [comment]
Awesome! Will give this a try soon

**Comment by borkdude** [comment]
What I did notice is that loading the medley code in nbb is a lot slower than compared to bb. I also noticed this when loading honeysql. It might be interesting to find where this difference comes from and to optimize this. Could be in SCI but could also be in edamame/tools.reader.

**Comment by borkdude** [comment]
Here is a repro in pure SCI (but not: unoptimized JS, in REPL):

```
$ clj -Sdeps '{:deps {org.clojure/clojurescript {:mvn/version "RELEASE"}}}' -M -m cljs.main -re node
ClojureScript 1.11.4
cljs.user=> (require '["fs" :as fs])
nil
cljs.user=> (def medley (fs/readFileSync "/tmp/medley/src/medley/core.cljc"))
#'cljs.user/medley
cljs.user=> (require '[sci.core :as sci])
nil
cljs.user=> (time (sci/eval-string (str medley "(medley.core/regexp? #\"foo\")") {:classes {'js goog/global} :features #{:cljs} :namespaces {'clojure.core {'IEditableCollection IEditableCollection 'MapEntry MapEntry 'PersistentQueue PersistentQueue 'UUID UUID 'uuid uuid}}}))
"Elapsed time: 101.397916 msecs"
```
