### ISSUE TITLE
Source map support

### ISSUE THREAD

**Issue by darky** [babashka/nbb#173]
**Is your feature request related to a problem? Please describe.**

Now any stack trace from node.js unuseful, because nbb doesn't support source maps.

**Describe the solution you'd like**

cljs -> js source map support

**Describe alternatives you've considered**

Much another compiled to JS programming languages support source maps (TypeScript, CoffeScript, e t. c.)
Even ClojureScript support source maps, maybe it can be adopt from ClojureScript :)

**Additional context**

![image](https://user-images.githubusercontent.com/1832800/164911690-d40ed3ed-659c-4d95-9f50-00265b3505f6.png)

**Comment by borkdude** [comment]
I don't think seeing stack traces from nbb itself (nbb/core.cljs, etc) will be very helpful, since nbb is an interpreter.

**Comment by darky** [comment]
It's ok to generate source maps on the fly from interpreter :)

Examples:
https://github.com/TypeStrong/ts-node
https://coffeescript.org/#nodejs-usage
https://livescript.net/#installation

**Comment by borkdude** [comment]
@darky Nbb is based on SCI and SCI does have a stacktrace it could show. But this only is about the source that is interpreted, not about nbb's own source. You can see that in action when you execute a script from the command line:

``` clojure
(ns foo)


(defn foo []
  (assoc :foo :bar))

(foo)
```

```
 $ nbb /tmp/foo.cljs
----- Error --------------------------------------
Message:  No protocol method IAssociative.-assoc defined for type object: :foo
Location: /tmp/foo.cljs:5:3

----- Context ------------------------------------
1: (ns foo)
2:
3:
4: (defn foo []
5:   (assoc :foo :bar))
     ^--- No protocol method IAssociative.-assoc defined for type object: :foo
6:
7: (foo)

----- Stack trace --------------------------------
clojure.core/assoc - <built-in>
foo/foo            - /tmp/foo.cljs:5:3
foo/foo            - /tmp/foo.cljs:4:1
foo                - /tmp/foo.cljs:7:1
```
