### ISSUE TITLE
Make `file` metadata work

### ISSUE THREAD

**Issue by benjamin-asdf** [babashka/nbb#184]
```clojure
(ns foo2)
(defn lul [] )
(:file (meta #'lul))
;; => nil
(contains? (meta #'lul) :file)
;; => true

```
:file is nil at the moment. 
It would allow cider and other tools to jump to definition.

**Comment by borkdude** [comment]
This seems to only affect nREPL (and maybe console REPL). Probably a matter of binding sci/file in the nREPL.

**Comment by benjamin-asdf** [comment]
I added file, info, eldoc, macroexpand. Merge request incomming. Next sick thing would be to jump to javascript sources.
