### ISSUE TITLE
`-main` as the default function to start

### ISSUE THREAD

**Issue by avelino** [babashka/nbb#203]
**Is your feature request related to a problem? Please describe.**
not

**Describe the solution you'd like**
nbb calls the functions that are in the body of the script, example:
```clj
(defn -main
  [& args]
  (prn "print in -main"))

(prn 123)
(prn "abc")
```

out:
```
123
abc
```

but it does not read a standard function like `-main`

**Additional context**
we don't always want to do a simple script, when we start a more organized software structure I do a `-main` to make it organized (any solution bigger than a script)

```clj
(defn -main
  [& args]
  (prn "print in -main"))

(-main)
```

**Comment by borkdude** [comment]
@avelino nbb executes the `-main` function when you invoke it with `nbb -m foo` where `-main` is defined in `foo.cljs`. This is the same behavior that Clojure has.
