### ISSUE TITLE
`reagent.core/adapt-react-class` missing symbol

### ISSUE THREAD

**Issue by alexandercarls** [babashka/nbb#214]
**version**

v0.5.112

**platform**

- macOS 12.2.1
- Node.js 16.5.1

**problem**

The symbol `adapt-react-class` is not present with nbb on `reagent.core`.
The function is used to create Reagent components from React components.

[Reagent Docs](https://github.com/reagent-project/reagent/blob/master/doc/InteropWithReact.md#creating-reagent-components-from-react-components)

On that note, the provided shortcut `:>` also does not work.

According to the [nbb's API documentation](https://github.com/babashka/nbb/blob/main/doc/api.md#reagentcore) it is missing as intended. Could this be added? My use case is highlighting code on the server and rendering it to static markup.

**repro**

The following works with ClojureScript via shadow-cljs

```clojure
(ns core
  (:require
   ["react-dom/server" :as ReactDomServer]
   ["prism-react-renderer" :refer [Prism]]
   ["prism-react-renderer$default" :as Highlight]
   [reagent.core :as r]))

(defn cake [code]
  [(r/adapt-react-class Highlight) {"Prism" Prism :code code :language "javascript"} (fn [params] (r/as-element [:div "Test"]))])

(ReactDomServer/renderToString (r/as-element (cake "const b = 3;")))
;; => "<div>Test</div>"
```

The error is `Could not resolve symbol: r/adapt-react-class`

It uses function as a child component ([Docs](https://github.com/reagent-project/reagent/blob/master/doc/InteropWithReact.md#example-function-as-child-components))

**expected behavior**

`"<div>Test</div>"`

**Comment by borkdude** [comment]
Should be there in the newest version on npm now

**Comment by alexandercarls** [comment]
Thank you @borkdude.

The symbol is present now. However `ReactDomServer/renderToString` (as well as  the reagent static version `render-to-static-markup`) now returns `Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`. 

The stack trace is not helpful. Or I am not aware on how to extract useful information there. Via `*e` from the REPL.

```clojure
#error {:message "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.", :data {:type :sci/error, :line 1, :column 1, :message "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.", :sci.impl/callstack #object[cljs.core.Volatile {:val ({:line 1, :column 1, :ns #object[hr core], :file "/Users/alca/private/site/src/core.cljs", :sci.impl/f-meta {:ns #object[hr reagent.dom.server], :name render-to-static-markup, :arglists ([component] [component compiler]), :doc "Turns a component into an HTML string, without data-react-id attributes, etc."}} {:line 1, :column 1, :ns #object[hr core], :file "/Users/alca/private/site/src/core.cljs", :sci.impl/f-meta {:ns #object[hr reagent.dom.server], :name render-to-static-markup, :arglists ([component] [component compiler]), :doc "Turns a component into an HTML string, without data-react-id attributes, etc."}})}], :file "/Users/alca/private/site/src/core.cljs"}, :cause #object[Error Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.]}
```

My guess is that there is some [internal fn](https://github.com/reagent-project/reagent/blob/master/src/reagent/core.cljs#L57) missing. Do you have any pointer on how to verify or find that out?

**Comment by alexandercarls** [comment]
The fn uses a `deftype`. Which is not yet supported. This is probably the cause.

https://github.com/reagent-project/reagent/blob/master/src/reagent/impl/template.cljs#L18,L22

**Comment by borkdude** [comment]
@alexandercarls I'm not sure what is the cause of the error, but deftype etc is not relevant here since the function call is made to the compiled reagent function, it is not interpreted in SCI. I'll take a look later, I can't find the issue myself either.

**Comment by alexandercarls** [comment]
@borkdude 

The following works. I am not sure why the default import with Node.js doesn't extract the `default` value by default for the library.

Note the `Highlight.default` bit there.

(renamed to prism.mjs)

```javascript
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import Highlight, { defaultProps } from "prism-react-renderer";

console.log(Highlight)
console.log(Highlight.default) // correct Function for "Highlight component"

const test = React.createElement(
    Highlight.default,
    { ...defaultProps, code: 'const b = 3;', language: 'javascript' },
    () => React.createElement('div', null, 'Test')
);

console.log(renderToStaticMarkup(test));
// <div>Test</div>
```

Given the above. The adjustment to the function for **nbb** works.

```clojure
(defn cake [code]
  [(r/adapt-react-class (.-default Highlight)) {"Prism" Prism :code code :language "javascript"} (fn [params] (r/as-element [:div "Test"]))])
  ```
  
However, this fails with **shadow-cljs**: `Assert failed: Component must not be nil`. It must be left without the `default` access.

Interesting.

**Comment by borkdude** [comment]
Interesting indeed. This sometimes happens with libraries that are compiled as typescript libraries. 
In nbb you often need an extra `$default` compared to target browser or nodejs in shadow, but if you use target esm in shadow, they will be exactly the same. Another way to write this in nbb without `adapt-react-class` would be with the `:>` syntax:

``` clojure
(ns example
  (:require
   ["prism-react-renderer$default" :as Highlight :refer [Prism]]
   [reagent.core :as r]
   [reagent.dom.server :as srv]))

(defn cake [code]
  [:> Highlight/default {"Prism" Prism :code code :language "javascript"}
   (fn [_params] (r/as-element [:div "Test"]))])

(prn (srv/render-to-string [cake "const b = 3;"]))
```

**Comment by alexandercarls** [comment]
Thank you very much for the explanation and the debugging help. It works fine now :)
