### ISSUE TITLE
bug: babashka/nbb-prismatic-schema `s/set-fn-validation!` isn't working as expected

### ISSUE THREAD

**Issue by omariosouto** [babashka/nbb#215]
## **version**

- `"nbb": "0.5.113"`
- `"@babashka/nbb-prismatic-schema":"0.5.113"`
- Package JSON File: https://github.com/devsoutinho/app-labs/blob/12174ad4518ec8861b72389224aa58f271b313cb/_servers/webproxy/package.json

## **platform**

- Node: v16.13.0
- NPM: v8.1.0
- Yarn: v1.22.17
- MacBook Pro (13-inch, M1, 2020) | Apple M1 | macOS MOnterey Version 12.4

## **problem**

- `s/set-fn-validation!` isn't working as expected

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/13791385/173250534-158ccb9c-6d7c-4f0f-bb2a-5a8a11aa07e8.png">

## **repro**

Just download these files in this commit: https://github.com/devsoutinho/app-labs/blob/12174ad4518ec8861b72389224aa58f271b313cb/_servers/webproxy/webproxy/app/diplomat/http_server.cljs#L9

## **expected behavior**

- When run `(s/set-fn-validation! false)` all validations must be disabled
- Right now this isn't happening

**Comment by borkdude** [comment]
We'll address this as part of schema compatibility when loading schema as a library from source
