### ISSUE TITLE
bug: babashka/nbb-prismatic-schema `s/defn` not avaiable to use

### ISSUE THREAD

**Issue by omariosouto** [babashka/nbb#216]
## **version**

- `"nbb": "0.5.113"`
- `"@babashka/nbb-prismatic-schema":"0.5.113"`
- Package JSON File: https://github.com/devsoutinho/app-labs/blob/main/_servers/webproxy/package.json

## **platform**

- Node: v16.13.0
- NPM: v8.1.0
- Yarn: v1.22.17
- MacBook Pro (13-inch, M1, 2020) | Apple M1 | macOS MOnterey Version 12.4

## **problem**

- `s/defn` isn't available
   - Even with the require as `[schema.core :as s :include-macros true]`
<img width="831" alt="image" src="https://user-images.githubusercontent.com/13791385/173250770-67c00a96-6297-47df-b506-6969e591b3ef.png">

## **repro**

- Just download these files in this [commit](https://github.com/devsoutinho/app-labs/blob/afac0832cd67346f48ef4830e91717a6166063d0/_servers/webproxy/webproxy/app/diplomat/http_server.cljs#L12).
- Error: `Message:  Could not resolve symbol: s/defn`

## **expected behavior**

- When using s/defn I should be able to use the macro that validates the function entry values and its output.

**Comment by borkdude** [comment]
@omariosouto Due to deployment difficulties I had to roll back schema / malli support for now :(.

**Comment by borkdude** [comment]
We'll address this as part of schema compatibility when loading schema as a library from source
