### ISSUE TITLE
I can't see logo in dark mode

### ISSUE THREAD

**Issue by andre2l2** [babashka/nbb#222]
**Is your feature request related to a problem? Please describe.**
My Github is in dark mode, but I can't see the logo, for example:

![Screenshot from 2022-06-24 13-02-37](https://user-images.githubusercontent.com/46267619/175574247-f9cc14e8-fa4a-4ae2-9bd8-93e78efd8215.png)

**Describe the solution you'd like**
I recommended add a white backgroud for example: 

### After

![nbb-with-name](https://user-images.githubusercontent.com/46267619/175575033-6eb51923-8100-431c-9356-7953bde5dde6.svg)

### Before:

![Group 1](https://user-images.githubusercontent.com/46267619/175575046-c8f9b60c-9285-450f-b35c-221353c106cb.svg)

**Comment by borkdude** [comment]
It's actually only the nbb letter you can't see right? Would making those green solve the problem as well?

**Comment by andre2l2** [comment]
Yes! You are sure, green is a great idea too

**Comment by borkdude** [comment]
Fixed
