### ISSUE TITLE
Bundler solution

### ISSUE THREAD

**Issue by borkdude** [babashka/nbb#230]
To work correctly with bundlers, nbb might support a mode which bundles one or multiple .cljs files into one string blob + a list of all dynamic imports, which is then spit out to a `.mjs` file which looks like this:

```
// import all dynamically imported libraries, perhaps deduplicated
import ...
import ...

await evalString( ... bundled .cljs code ...)
```

Using this mode, nbb scripts should be able to be packaged up with tools like ncc.

/cc @logseq-cldwalker

**Comment by logseq-cldwalker** [comment]
This sounds promising! Sounds like it replaces manually writing something like https://github.com/borkdude/nbb-action-example/blob/main/index.mjs for `action.cljs` with an invocation of this mode. I'd be happy to test this mode with https://github.com/logseq/graph-validator if you decide to support this
