### ISSUE TITLE
nrepl-server doesn't respond 'done' status on exception

### ISSUE THREAD

**Issue by liquidz** [babashka/nbb#236]
**version**

* v0.6.124

**platform**

* macOS Monterey (M1 Max)

**problem**

* nrepl-server doesn't respond 'done' status on exception

**repro**

* Start nREPL server
  * `nbb nrepl-server :port 1337 :host 0.0.0.0`
* Connect to nREPL server
  * `nc localhost 1337`
  * Send `clone` op
    * `d2:op5:clonee`
    *  > d2:idle11:new-session36:f612ad84-7f2b-457e-b679-3ce6ed2ac2fb6:statusl4:doneee
  * Send `info` op with unknown ns
    * `d2:op4:info3:sym3:foo2:ns8:foo.core7:session36:f612ad84-7f2b-457e-b679-3ce6ed2ac2fbe`
    * > d2:ex264:#error {:message "No namespace: foo.core found", :data {:type :sci/error, :line 2, :column 1, :message "No namespace: foo.core found", :sci.impl/callstack #object[cljs.core.Volatile {:val ()}], :file nil}, :cause #object[Error Error: No namespace: foo.core found]}2:idle7:session36:f612ad84-7f2b-457e-b679-3ce6ed2ac2fb6:statuse
    * If you look at the last part, you will see that done is not returned as a status as in `6:statuse`

**expected behavior**

The status should contain `done` like `6:statusl4:doneee`.

The `done` status is defined as `set` in the following place.
https://github.com/babashka/nbb/blob/f9ce0882934659f273f5f81f5ab1901e05913526/src/nbb/impl/nrepl_server.cljs#L222
And bencode encoder handles only `vector` and `nil` as lists.
https://github.com/babashka/nbb/blob/f9ce0882934659f273f5f81f5ab1901e05913526/src/nbb/impl/bencode.cljs#L76
So `set?` should be added to the above place.

**Comment by borkdude** [comment]
Thanks for pointing that out.
