### ISSUE TITLE
config.edn with script argument doesn't seem to work

### ISSUE THREAD

**Issue by logseq-cldwalker** [babashka/nbb#245]
Hi. Trying out the latest `--config` functionality and ~~not sure if I'm doing something wrong~~ I think there's a race condition /cc @lilactown 

---
**version**

0.7.132

**platform**

osx 12.0.1

**problem**

Use `--config` with a script file and see that nbb is unable to load the dependency ns

**repro**

```sh
nbb --config malli.edn malli.cljs
----- Error --------------------------------------
Message:  Could not find namespace: malli.core
Could not find namespace: malli.core
```

malli.edn:
```clojure
{:deps {metosin/malli {:git/url "https://github.com/borkdude/malli" :git/sha "e400bbcdab09b21dc42d82f90400f60f85af6bd9"}}}
```

malli.cljs:
```clojure
(ns malli
  (:require [malli.core :as m]))

(def non-empty-string
  (m/schema [:string {:min 1}]))

(prn (m/validate non-empty-string ""))
(prn (m/validate non-empty-string "kikka"))
```
EDIT: If I put `(nbb.core/await (js/Promise. (fn [r] (js/setTimeout r 100))))` before the `ns` declaration. I no longer see the issue. There seems to be a race condition

**expected behavior**

Expected to see results as I see them in the repl:
```
nbb --config malli.edn
Welcome to nbb v0.7.132!
user=> (require '[malli])
false
true
nil
```

**Comment by borkdude** [comment]
@logseq-cldwalker I think the race condition should be solved now, can you try with the latest version?

**Comment by logseq-cldwalker** [comment]
Works great with 0.7.135. Thanks!
