### ISSUE TITLE
Include all goog.object functions

### ISSUE THREAD

**Issue by dehli** [babashka/nbb#247]
**Is your feature request related to a problem? Please describe.**
I'd like to use certain `goog.object` functions via `nbb`  that aren't available (such as `getAllPropertyNames`).

**Describe the solution you'd like**
I'd like to have access to all `goog.object` functions from within `nbb`.

**Describe alternatives you've considered**
I could rewrite the code that uses the non-included `goog.object` functions.

**Additional context**
I unfortunately didn't read the `dev.md` until after coming up with a solution so I have a potential PR here: https://github.com/babashka/nbb/pull/248

**Comment by borkdude** [comment]
@dehli Can you check, when running bb release with main + bb release with this PR what the total size difference is?

We may want to make goog.object lazy if this has an impact on startup time. I'll run some tests myself too.

**Comment by dehli** [comment]
When running `bb release` with the two branches I'm getting very similar sizes. This is the size difference of `:nbb_core` (gzipped).

|                  | #247          |   main        |
|---------------|----------------|---------------|
| :nbb_core | 215.51KB  | 214.07 KB  | 

[247-report.html](https://github.com/babashka/nbb/files/9409774/247-report.html.txt)
[main-report.html](https://github.com/babashka/nbb/files/9409733/main-report.html.txt)

When drilling down into the google-closure-library, I can see that `goog/object/object.js` contributes 3.48 KB on my branch, whereas it contributes 703 bytes on main (this report is very cool btw).

![image](https://user-images.githubusercontent.com/5856011/186240893-2fcd635d-f790-4849-ad56-7834aec10a56.png)

I'll do some investigation on startup time as well / lazy loading.

**Comment by dehli** [comment]
Startup time seems to be unaffected from my testing. I used the following babashka task to compare the two start-up times:

```clj
(let [num   1000
      nbb   (fn [] (shell "./cli.js -e nil"))
      start (java.time.LocalDateTime/now)
      _     (dorun (take num (repeatedly nbb)))
      end   (java.time.LocalDateTime/now)
      diff  (java.time.Duration/between start end)]

  (println (/ (.toMillis diff) (float num)))
```

| #247           | main
|----------------|-------------------|
157.261ms  |    158.860ms |

**Comment by borkdude** [comment]
OK, this is an insignificant different and I'm ok with adding everything from goog.object in a non-lazy fashion.
