### ISSUE TITLE
nbb.edn should update classpath based on :paths

### ISSUE THREAD

**Issue by bolivier** [babashka/nbb#254]
Nontrivial scripts (and TUI apps) will likely require updating the classpath (for organization or dependencies).  Right now, the only (I think) tool for managing that is a `classpath` env var, which can be unwieldly as a project grows.  It can also cause trouble between projects.

I think it would be reasonable to have nbb read from a bb.edn file like babashka does.

There could be problems determining some details if a project uses nbb and bb, so it could be necessary to use a different name (nbb.edn, for example).

I'm not especially familiar with this project; but I'm an enthusiast, so I'd be happy to work on this.

**Comment by borkdude** [comment]
nbb reads from `nbb.edn`

**Comment by borkdude** [comment]
I guess we still need to document this, I'm surprised we didn't @lilactown :)

**Comment by bolivier** [comment]
@borkdude is there a way to configure the classpath via `nbb.edn`?

**Comment by borkdude** [comment]
@bolivier `nbb.edn` supports `:deps` and `:paths` just like `bb.edn` - and these deps are fetched using `bb` so it assumes you have `bb` installed.

**Comment by bolivier** [comment]
@borkdude Does `:paths` update the classpath?  If I have 

```clojure
;; nbb.edn
{:paths ["src"]}
```

```clojure
;; src/core.cljs
(ns core)

(println "hi")
```

and I run `nbb -m core` I get a "Could not find namespace" error.

**Comment by borkdude** [comment]
@bolivier What version of `nbb` are you using?

**Comment by borkdude** [comment]
I can reproduce the issue. It seems `:paths` isn't taken into account yet.

**Comment by borkdude** [comment]
I changed the title of this issue to reflect the problem.

**Comment by bolivier** [comment]
```
$ nbb -v
nbb v0.7.131
```

**Comment by borkdude** [comment]
@bolivier If the offer still stands:

> I'm not especially familiar with this project; but I'm an enthusiast, so I'd be happy to work on this.

then you are invited to take a look.

**Comment by borkdude** [comment]
Published
