### ISSUE TITLE
No matching clause: use-macros

### ISSUE THREAD

**Issue by Ramblurr** [babashka/nbb#263]
**version**

nbb 1.0.136

**platform**

Linux, node js v16.15.1

**problem**

Using a CLJC dependency that has `:use-macros` causes an error:

```
----- Error --------------------------------------
Message:  No matching clause: use-macros
No matching clause: use-macros
```

Grepping through the code, it looks like the problem lies in a transitive dependency "instaparse":

https://github.com/Engelberg/instaparse/blob/master/src/instaparse/gll.cljc#L35

**repro**

Here's the script: https://github.com/Ramblurr/svg-to-hiccup/blob/main/cleanup.cljs

1. `git clone https://github.com/Ramblurr/svg-to-hiccup.git`
2. `cd svg-to-hiccup`
3. `bb npm-install`
4. `bb write-deps`
5. `npx nbb -m cleanup test.svg`

**expected behavior**

Well, I guess it should just work?

I heard in your nbb video presentation that not all of clojure is implemented yet, so this could well be expected for now. Just thought I'd raise it to your attention.

**Comment by Ramblurr** [comment]
Hmm.. ok I understand. 

I found this other cljs ns for converting html to hiccup with hickory: https://github.com/coldnew/html2hiccup/blob/master/src/cljs/html2hiccup/converter.cljs

This time it is using hickory underthe hood, and the error is:

```
----- Error --------------------------------------
Message:  Cannot read properties of undefined (reading 'ATTRIBUTE_NODE')
Location: /var/home/ramblurr/src/svg-to-hiccup/.nbb/.cache/41cac4922ec9360a4b039adc50f8c21ec3d2f961/nbb-deps/hickory/core.cljs:37:3

----- Context ------------------------------------
33:      nodes created by parse or parse-fragment already do."))
34: 
35: (defn node-type
36:   [type]
37:   (aget js/Node (str type "_NODE")))
      ^--- Cannot read properties of undefined (reading 'ATTRIBUTE_NODE')
38: 
39: (def Attribute (node-type "ATTRIBUTE"))
40: (def Comment (node-type "COMMENT"))
41: (def Document (node-type "DOCUMENT"))
42: (def DocumentType (node-type "DOCUMENT_TYPE"))

----- Stack trace --------------------------------
clojure.core/aget      - <built-in> 
hickory.core/node-type - /var/home/ramblurr/src/svg-to-hiccup/.nbb/.cache/41cac4922ec9360a4b039adc50f8c21ec3d2f961/nbb-deps/hickory/core.cljs:37:3 
hickory.core/node-type - /var/home/ramblurr/src/svg-to-hiccup/.nbb/.cache/41cac4922ec9360a4b039adc50f8c21ec3d2f961/nbb-deps/hickory/core.cljs:35:1 
hickory.core           - /var/home/ramblurr/src/svg-to-hiccup/.nbb/.cache/41cac4922ec9360a4b039adc50f8c21ec3d2f961/nbb-deps/hickory/core.cljs:39:16 
```

I updated my repo to use this example, so you can take it for a spin. Though maybe I should open a new issue?

**Comment by borkdude** [comment]
@Ramblurr I think the issue there is that `js/Node` works in the browser but not in Node.js.

To build an HTML -> Hiccup thing, I think it might be easiest to start from scratch with a Node library which can parse HTML to objects, then transform those objects to hiccup vectors using pre-walk. My suspicion is that this is a 10-20 line script.

**Comment by Ramblurr** [comment]
Ah you're right, of course `js/Node` is a [`Node`](https://developer.mozilla.org/en-US/docs/Web/API/Node). My brain parsed that as something node.js related.

**Comment by borkdude** [comment]
I've just added an example to the repo:

It's probably incomplete but you get the idea.

<img width="1471" alt="Screenshot 2022-10-14 at 18 09 34" src="https://user-images.githubusercontent.com/284934/195892398-a7cc15fc-ac3e-44e1-9b7c-bc474ba02ed3.png">

**Comment by Ramblurr** [comment]
Haha, you didn't have to do that.. though it's a nice example for nbb!

In the same time I ended up with the following, using a different library.

![scrn-2022-10-14-18-58-46](https://user-images.githubusercontent.com/14830/195901693-8dddc868-142f-4e58-9de4-cb7f08679c38.png) 
[code](https://github.com/Ramblurr/svg-to-hiccup/blob/main/svg_to_hiccup.cljs#L1-L24)

Your `clojure.walk/walk` solution is much more elegant.

**Comment by borkdude** [comment]
Actually I like your solution better :) walk isn't really necessary here:

``` clojure
(def root (parse "<ul id=\"list\" ><li>Hello World</li></ul>"))

(defn html->hiccup [elt]
  (cond
    (instance? html/HTMLElement elt)
    (into (cond-> [(keyword (str/lower-case (str (.-tagName elt))))]
            (pos? (count (js/Object.values (.-attributes elt))))
            (conj (js->clj (.-attributes elt) :keywordize-keys true)))
          (map html->hiccup (.-childNodes elt)))
    (instance? html/TextNode elt)
    (.-text elt)
    :else
    (do
      (prn elt ((js/eval "(x) => typeof(x)" elt)))
      elt)))

(run! pprint (map html->hiccup (.-childNodes root)))
```

**Comment by borkdude** [comment]
If you don't mind, I'll close this issue as I don't think there is a reliable solution for the original problem. The style in which nbb works best is to use Node JS library and glue those together using CLJS core or built-in libs.

**Comment by borkdude** [comment]
Posthtml is indeed a nicer API:

``` clojure
(ns example
  (:require
   ["posthtml-parser" :refer [parser]]
   [clojure.pprint :refer [pprint]]))

(defn parse [s]
  (js->clj (parser s) :keywordize-keys true))

(defn html->hiccup [{:keys [tag attrs content] :as elt}]
  (if tag
    (into (cond-> [(keyword tag)]
            (seq attrs) (conj attrs))
          (map html->hiccup content))
    elt))

(run! (comp pprint html->hiccup) (parse "<ul id=\"list\" ><li>Hello World</li></ul>"))
```

**Comment by Ramblurr** [comment]
Many thanks for the assistance! nbb is awesome.

**Comment by borkdude** [comment]
Thanks. Added `clojure.zip` in 1.0.137 which should allow one to load `hickory.select` from source. Example updated:

https://github.com/babashka/nbb/blob/main/examples/posthtml-parser/example.cljs
