### ISSUE TITLE
Some clojure.test vars missing

### ISSUE THREAD

**Issue by chr15m** [babashka/nbb#277]
I'm running tests in my project with nbb and running into issues with missing built-ins:

```
Unresolved var: t/run-test
```

and

```
Could not find namespace: clojure.test.tap
```

Would be great if these were available, thanks!

**Comment by borkdude** [comment]
I can't find `run-test` and `clojure.test.tap` in ClojureScript... should they be in there?

```
$ clojure -M:cljs -re node
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
-re (No such file or directory)

Full report at:
/var/folders/j9/xmjlcym958b1fr0npsp9msvh0000gn/T/clojure-2446584001117641703.edn
```

```
$ clojure -M:cljs -m cljs.main -re node
ClojureScript 1.11.54
cljs.user=> (require '[clojure.test.tap])
Unexpected error (ExceptionInfo) compiling at (<cljs repl>:1:1).
No such namespace: clojure.test.tap, could not locate clojure/test/tap.cljs, clojure/test/tap.cljc, or JavaScript source providing "clojure.test.tap" at line 1 <cljs repl>
cljs.user=> (require '[cljs.test])
nil
cljs.user=> (cljs.test/run-test 'foo)
WARNING: Use of undeclared Var cljs.test/run-test at line 1 <cljs repl>
Execution error (TypeError) at (<cljs repl>:1).
Cannot read properties of undefined (reading 'call')
```

**Comment by chr15m** [comment]
@borkdude No it seems they are only i Clojure, my apologies!

**Comment by borkdude** [comment]
No worries. I think `run-test` should be added to CLJS to be in sync with Clojure 1.11. I'll make an issue

**Comment by borkdude** [comment]
@robobun

``` javascript
import { loadString } from 'nbb'

await loadString(`

(defn foo [] "hello")
(prn (str (foo) " there!"))

`)
```

**Comment by robobun** [comment]
@borkdude here you go!
```tsx
"hello there!"
```
<details>
  <summary>Code</summary>
  
```tsx
import { loadString } from 'nbb'

await loadString(`

(defn foo [] "hello")
(prn (str (foo) " there!"))

`)
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by borkdude** [comment]
I think we can now implement this since I added `t/run-test` to CLJS proper :)

**Comment by chr15m** [comment]
I found a workaround for this for running one specific test:
```
(t/run-all-tests #"sitefoxtest.e2etests/nbb-forms")
```

**Comment by borkdude** [comment]
My suggestion would be to just add the `run-test` var to sci.configs and then update nbb

**Comment by borkdude** [comment]
done

**Comment by chr15m** [comment]
> My suggestion would be to just add the `run-test` var to sci.configs and then update nbb

You're right, I should learn how to hack on `nbb` myself so I can contribute. Thanks for pushing the fix!
