### ISSUE TITLE
Add implied script root to default classpath

### ISSUE THREAD

**Issue by milelo** [babashka/nbb#281]
**Is your feature request related to a problem? Please describe.**
I have an issue with the nbb classpath; I need to explicitly add my nbb script folders absolute path to the nbb classpath to enable nbb to find a local dependent library.

My nbb executable scripts are together in the root of my nbb project along with package.json etc. I've added this to my Linux PATH so they can be called from other locations.

The scripts use #! but I have found I also need to set the classpath: #!/usr/bin/env -S nbb -cp \<path to script project root\>.
It doesn't mater if the library is in the root (:require [utils]) or a folder (:require [lib.utils]), the classpath is still required.

nbb finds the dependent packages ok without the classpath. Similarly I expected nbb to find local cljs libraries without the explicit classpath.

Message:  Could not find namespace: lib.utils
nbb v1.1.146

**Describe the solution you'd like**
I would like script root folder as implied by the invoked script namespace to be added to the default classpath. This would enable local libraries :required using standard Clojure namespace conventions to be located.

**Describe alternatives you've considered**
I'm currently using an explicit classpath. It may be possible to dynamically add to the classpath in the script or use explicit path references in the :requires but this solution would solve the problem without any special handling.

**Additional context**

This would also enable symlinks on the system PATH to nbb #! scripts to be supported without an explicit classpath or special library requires syntax.

**Comment by milelo** [comment]
My comment:
"This would also enable symlinks on the system PATH to nbb #! scripts to be supported without an explicit classpath or special library requires syntax" 
appears to be wishful thinking. 
I've tried it, in that case the javascript libraries (in node_modules) aren't found either so this would require some additional handling.

**Comment by borkdude** [comment]
Perhaps we can resolve the symlink in nbb first, I think that would be the solution to that issue

**Comment by borkdude** [comment]
@milelo Is is possible to make an example project which exhibits this problem?

**Comment by cldwalker** [comment]
I'm encountering a variant of this issue for nbb.edn and executables with #297 

> Perhaps we can resolve the symlink in nbb first, I think that would be the solution to that issue

I'm not sure if this enables the nbb.edn case unless it means changing the working directory of the script. For nbb.edn, it looks like [local-nbb-edn](https://github.com/babashka/nbb/blob/722d3c0e2e52cf34e075f3d8fb99b44725202301/src/nbb/api.cljs#L21) could check for nbb.edn in the executable directory or the current directory

**Comment by borkdude** [comment]
Yeah, I think nbb should just use the classpath (either implicit or explicit via nbb.edn) of the script invoked, but there might be exceptions, like: you're invoking a script in subdir of a repo that has an nbb.edn at the root?

**Comment by cldwalker** [comment]
I'm not specifically running into that case but I could be invoking the script from any directory since it's an executable on `$PATH`. I mentioned `local-nbb-edn` because it looks the global executable can't currently find it's packaged nbb.edn before it sets the classpath. Updated instructions in https://github.com/cldwalker/nbb-deps-repro if it helps

**Comment by borkdude** [comment]
If you create an (optionally empty) `nbb.edn` to indicate the project root relative to your script, this will work since #297 is fixed.
