### ISSUE TITLE
Could not resolve symbol: p/future

### ISSUE THREAD

**Issue by avelino** [babashka/nbb#282]
**version**

v1.0.144

**platform**

macOS

**problem**

Could not resolve symbol: p/future

**repro**

```
(ns example
  (:require [promesa.core :as p]))

(p/future (fn [] (prn 123)))
```
**expected behavior**

find the `future` symbol of package `promesa`

**Comment by borkdude** [comment]
This should be added to https://github.com/babashka/sci.configs and then the sci.configs dep should be bumped here. 

Feel free to make a PR or else I will get to it sometime soon.

**Comment by avelino** [comment]
@borkdude send, after revising PR in `sci.configs` update the `:git/sha` in `deps.edn` here

**Comment by avelino** [comment]
Fixed this commit
https://github.com/babashka/nbb/commit/40e1483db557d565dc6e01e967575ec26e05d230

Thanks @borkdude
