### ISSUE TITLE
clojure.pprint/cl-format does not exist

### ISSUE THREAD

**Issue by milelo** [babashka/nbb#285]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**

nbb v1.1.146

**platform**

Debian

**problem**

[https://github.com/babashka/nbb/blob/main/doc/api.md]()
declares that the namespace clojure.pprint is included however 
(:require [clojure.pprint :refer [cl-format]]) 
reports:
Message:  cl-format does not exist

**repro**

[ Please provide a minimal working reproduction of the problem ]

**expected behavior**

[ What is the behavior you expected to see? Please provide a minimal working example ]

**Comment by borkdude** [comment]
Publishing as 1.1.149
