### ISSUE TITLE
VSCode + Calva + nRepl - typing * causes SyntaxError in nbb

### ISSUE THREAD

**Issue by davidyang** [babashka/nbb#288]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**

nbb v1.1.151

**platform**

MacOS 13
Node 16.15.0

**problem**

- Start a nbb script
- Start a nREPL server 
- Connect from VSCode Calva
- Type `*`

I get this error in the console:

```
SyntaxError: Invalid regular expression: /*/: Nothing to repeat
    at new RegExp (<anonymous>)
    at Object.$APP.xj (file:///Users/davidtest/node_modules/nbb/lib/nbb_core.js:150:174)
    at file:///Users/davidtest/node_modules/nbb/lib/nbb_api.js:15:492
    at file:///Users/davidtest/node_modules/nbb/lib/nbb_core.js:974:214
    at file:///Users/davidtest/node_modules/nbb/lib/nbb_core.js:974:227
    at Nf (file:///Users/davidtest/node_modules/nbb/lib/nbb_core.js:92:145)
    at $APP.Mf.$APP.l.ea (file:///Users/davidtest/node_modules/nbb/lib/nbb_core.js:905:22)
    at Object.$APP.w (file:///Users/davidtest/node_modules/nbb/lib/nbb_core.js:67:94)
    at file:///Users/davidtest/node_modules/nbb/lib/nbb_core.js:917:70
    at Nf (file:///Users/davidtest/node_modules/nbb/lib/nbb_core.js:92:145)

```

**repro**

This file as test.cljs works for me to reproduce the error whenever I type `*`

```
(ns test
  (:require  [nbb.nrepl-server :as nrepl]))

(nrepl/start-server! {:port 1337})

*
```

**expected behavior**

No syntax error.

**Comment by borkdude** [comment]
Hi @davidyang - I have problems reproducing this with Calva and nbb (1.1.151). Maybe I'm missing something?

<img width="639" alt="Screenshot 2022-12-14 at 16 06 46" src="https://user-images.githubusercontent.com/284934/207632291-19ce25d2-4c74-448e-b634-d31b443626bd.png">

**Comment by davidyang** [comment]
Thanks for the quick response Michiel!

It seems like it happens when I try to autocomplete, not evaluate the
expression.

So if I put cursor right after the * and press Ctrl-Space I get the error
in the console.  Evaluation continues to work.

It seems to me like maybe Calva is trying to get some info from LSP and nbb
is trying to read the file and having issues?

**Comment by borkdude** [comment]
OK, the culprit is likely here:

https://github.com/babashka/nbb/blob/e2b5679a5340c939fc3e7a8b2aebbdd510eb4d48/src/nbb/impl/repl_utils.cljs#L23

which can be reproduced using:

```
cljs.user=> (re-pattern "*")
Execution error (SyntaxError) at (<cljs repl>:1).
Invalid regular expression: nothing to repeat
```

which can be fixed like this:

```
cljs.user=> (re-pattern (str/replace "*" #"[.*+?^${}()|[\]\\]" "\\$&"))
#"\*"
cljs.user=> (re-find (re-pattern (str/replace "*" #"[.*+?^${}()|[\]\\]" "\\$&")) "foo*foo")
```

(cf https://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex)

**Comment by borkdude** [comment]
Thanks for the issue. Now publishing 1.1.152.

**Comment by davidyang** [comment]
Awesome - thanks for the quick response!
