### ISSUE TITLE
*file* always `nil` inside a `p/let`

### ISSUE THREAD

**Issue by gdw2** [babashka/nbb#291]
**version** 1.1.152

**platform** nix pkgs on ubuntu.  node 18.12.1

**problem**

This prints out the file name:

```clojure
(ns example
  (:require  [nbb.core :refer [*file*]]))

(prn *file*)
```

But this prints out `nil`.  Not what I expected.

```clojure
(ns example
  (:require  [nbb.core :refer [*file*]]
             [promesa.core :as p]))

(p/let []
  (prn *file*))
```

**Comment by borkdude** [comment]
If it works, then that was purely co-incidental or an effect of code running async, but just in time.
The only reliable way of capturing `*file*` is to do it as you did it in the first example.

**Comment by borkdude** [comment]
@gdw2 Yes, `*file*` is a dynamic var which is bound when the file is evaluated, but by when async code runs, this dynamic var isn't bound anymore (could, be, but not guaranteed).
