### ISSUE TITLE
swap-vals! missing in nbb core namespace

### ISSUE THREAD

**Issue by mmilian** [babashka/nbb#295]
When:

`(def store (atom []))`
`(swap-vals! store conj 1) `

I get:
; Could not resolve symbol: swap-vals!

`#error {:message "Could not resolve symbol: swap-vals!", :data {:type :sci/error, :line 1, :column 1, :message "Could not resolve symbol: swap-vals!", :sci.impl/callstack`

Version: 
nbb v1.1.156

**Comment by borkdude** [comment]
Publishing as 1.1.157
