### ISSUE TITLE
deps from nbb.edn are not in classpath when called by node from a bin script

### ISSUE THREAD

**Issue by cldwalker** [babashka/nbb#297]
Hi @borkdude. Encountered this while doing something with nbb-logseq but this effect nbb users as well. Cheers

----

**version**

1.1.157

**platform**

osx 12.0.1 and node 16.13.1

**problem**
My problem is similar to https://github.com/babashka/nbb/issues/270 except I'm invoking node as a bin executable instead of in the current project directory. I encountered this while trying to turn [this nbb-logseq script](https://github.com/logseq/nbb-logseq/blob/main/examples/from-js/ast.js) into an executable and following the directions from https://github.com/babashka/nbb/tree/b3e2418011e205559edad4677b6e26ddd66c74ea/doc/publish . 

I don't have a great workaround for this except to hardcode `.nbb/cache/X/nbb-deps` directories in executables which seems brittle. 

My initial use case is to globally install scripts. If this is fixed, I think it also enables nbb packages to be published with nbb.edn and to be consumed by node users who have bb, which would be pretty awesome.

**repro**

https://github.com/cldwalker/nbb-deps-repro - a modified version of #270 

**expected behavior**

I expected to see the script load the nbb deps successfully

**Comment by borkdude** [comment]
Probably related to https://github.com/babashka/nbb/issues/281

**Comment by cldwalker** [comment]
Ah, missed that. Thanks for the pointer

**Comment by borkdude** [comment]
I'm open to a PR around this and #281 or I'll probably look into this sometime in the next weeks.

**Comment by cldwalker** [comment]
For this issue, [local-nbb-edn](https://github.com/babashka/nbb/blob/722d3c0e2e52cf34e075f3d8fb99b44725202301/src/nbb/api.cljs#L21) is looking for `nbb.edn` in the wrong directory. One way I can solve this is by passing the executable's current directory to that fn through `loadFile/loadString`. In other words, the executable would pass the value of `__dirname` from [this example](https://github.com/babashka/nbb/tree/b3e2418011e205559edad4677b6e26ddd66c74ea/doc/publish) to `local-nbb-edn` . Would you be open to a PR that provides such an option? I'm not sure if this overlaps with #281 as that seems to be a larger change with classpath which this use case doesn't necessarily need

**Comment by borkdude** [comment]
Yes but that might not be the only place that needs a little change. 

Btw, another way to solve this problem is to make an "uberscript" which you can do with the bundle command:

https://github.com/babashka/nbb/tree/main/doc/bundle

**Comment by borkdude** [comment]
Should work in 1.2.166 (building on CI right now)

**Comment by borkdude** [comment]
Need to fix one more thing, the `.nbb` directory should be created relative to the `nbb.edn` I think

**Comment by cldwalker** [comment]
Thanks! ❤️ 🕺  Simpler solution than I was thinking of and works great with nbb-logseq. Released a new nbb-logseq version for this

**Comment by borkdude** [comment]
Note that the newest nbb version is [v1.2.169](https://github.com/babashka/nbb/releases/tag/v1.2.169)
