### ISSUE TITLE
Unexpected behavior using with-out-str with print-error-report

### ISSUE THREAD

**Issue by alpox** [babashka/nbb#300]
**version**

1.2.159

**platform**

macOS Ventura 13.1
Node v18.12.1

**problem**

When using the new error reporting function `print-error-report` with `with-out-str` I get back an empty string and the error report still writes to the original output. E.g.:

```clj
(with-out-str (print-error-report e))
```

Results in an empty string.

**repro**

```clj
(def result
  (try 
    (assoc :foo :bar)
    (catch ^:sci/error js/Error e
      (with-out-str (print-error-report e)))))

(prn result)
```

The above code prints an empty string.

**expected behavior**

The code in `repro` should print the actual error message stored in `result`.

**Comment by borkdude** [comment]
Publishing as 1.2.160. The way to do this now is to capture the output of `*print-err-fn*`:

``` clojure
(require '[nbb.error :refer [print-error-report]]
         '[clojure.string :as str])

(def result
  (try
    (assoc :foo :bar)
    (catch ^:sci/error js/Error e
      (let [lines (atom [])]
        (binding [*print-err-fn* #(swap! lines conj %)]
          (print-error-report e))
        (str/join "\n" @lines)))))

(println "Error:")
(println result)
```

**Comment by alpox** [comment]
Awesome. Thanks a lot again.
