### ISSUE TITLE
Support :init option when creating a repl

### ISSUE THREAD

**Issue by eccentric-j** [babashka/nbb#315]
**Is your feature request related to a problem? Please describe.**
When creating a repl with `(nbb.repl/repl)` it could take an :init option that evaluates forms to intern bindings within the repl.

**Describe the solution you'd like**
A similar implementation to core repl `:init` https://insideclojure.org/2020/02/11/custom-repl/ but in Slack you mentioned wrapping it in a promise for require support.

**Describe alternatives you've considered**
It might be possible to loop through the symbols of an existing namespace and create local defs to make a namespace available, but feels non-idiomatic, plus would likely not work with macros.

**Additional context**
Use case is I’m updating the nbb replit and thought it would be helpful if one could fire up the repl and instantly write something like:

```clojure
(p/-> (js/fetch “https://google.com”) (.text) (println))
```

**Questions**

What would the usage look like? Based on what was discussed, I’m picturing:

```clojure
(require ‘[promesa.core :as p])

(repl/repl
  {:init (p/do (apply require ‘[[promesa.core] :as p]
                                [clojure.repl :refer [doc]]
                                [cljs.pprint :refer [pp pprint]]))})
```

**Comment by borkdude** [comment]
`:init` would be a function, like in `clojure.main/repl`

**Comment by borkdude** [comment]
the function can return a promise or an ordinary function and will then be chained onto the rest of the stuff here:

https://github.com/babashka/nbb/blob/b9c26314dc4546bbe253035955e79c9ecba51862/src/nbb/impl/repl.cljs#L203

**Comment by eccentric-j** [comment]
That helps a lot! Last question: How should it deal with the optionality?

```clojure
(-> ...
    (.then (if (ifn? (:init opts)) (:init opts) identity)))
```

**Comment by borkdude** [comment]
I'd say:

```
(let [init (:init opts identity)]
  (.then (...) init)
```

**Comment by eccentric-j** [comment]
Should that let also contain a runtime check like?

```clojure
(when-not (ifn? init)
  (js/throw (js/Error. ":init must be a function")))
```

**Comment by borkdude** [comment]
I would say that's overkill

**Comment by borkdude** [comment]
@eccentric-j Maybe this would also be nice to have for the nREPL server? But I'll close the existing issue for now.
