### ISSUE TITLE
PersistentQueue.EMPTY is nil

### ISSUE THREAD

**Issue by dmg46664** [babashka/nbb#323]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**

1.2.173

**platform**

Node.js v19.8.1

**problem** & **repro**

```
(comment
  ;; "nbb" "1.0.142" works
  ;; "nbb" "1.2.173" regression
  (peek (into cljs.core/PersistentQueue.EMPTY [:a :b :c])) ;; nbb => :c
  (peek (into cljs.core/PersistentQueue.EMPTY [:a :b :c])) ;; shadow-cljs => :a
  )
```

**expected behavior**

As per above.

**Discussion**
https://clojurians.slack.com/archives/C029PTWD3HR/p1682156505265399

**Comment by borkdude** [comment]
Workaround: `(into #queue [:a :b :c])`

**Comment by dmg46664** [comment]
Nice one! Using the workaround (which is preferable).
