### ISSUE TITLE
Incrementing a keyword

### ISSUE THREAD

**Issue by gdw2** [babashka/nbb#325]
```
Welcome to nbb v1.2.173!
user=> (inc :foo)
":foo1"
```

Expected:  Clojure throws an exception.  Clojurescript gives a warning.  Maybe the-above is fine?

**Comment by borkdude** [comment]
Yes, in CLJS there's not much we can do. The CLJS compiler gives a warning but nbb is based on SCI which is an interpreter. I recommend using a linter like clj-kondo which will catch this:

<img width="563" alt="Screenshot 2023-05-02 at 19 07 24" src="https://user-images.githubusercontent.com/284934/235735905-79234cee-bda4-400c-b564-0e724cf1e563.png">
