### ISSUE TITLE
nrepl: println does not print the NL when called from inside js timeout

### ISSUE THREAD

**Issue by ikappaki** [babashka/nbb#330]
**version**

nbb v1.2.169

**platform**

any

**problem**

When `println` is called from inside  `js/setTimeout`, no newline is printed at the end.

**repro**

1. Run `nbb nrepl-server` and connect it to with your favorite editor.
2. Evaluate the following two println statements on the nREPL
```clojure
(js/setTimeout #(do (println 1) (println 2)))
```
3. it concatenates the 2 println statements into one line.
```12```

**expected behavior**

It should also print the newline of each `println` statement.
```
1
2
```

Thanks

**Comment by borkdude** [comment]
Did you mean to provide a number as a timeout here as well? `(js/setTimeout #(do (println 1) (println 2)))`

**Comment by ikappaki** [comment]
> Did you mean to provide a number as a timeout here as well? `(js/setTimeout #(do (println 1) (println 2)))`

It doesn't make a difference, I was trying to do the minimal reproduction so [I omitted the second argument](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) for brevity 😄. 

``` clojure
(js/setTimeout #(do (println 1) (println 2)) 1000)
;; 12
```

The actual case manifested itself after a promesa `p/delay` within a `p/do` block.

**Comment by ikappaki** [comment]
Hi @borkdude,

would you be able to provide some advice on the above please. It seems to me this could be `sci` related and has to do with delayed execution of a promise?

I can't see something suspicious in the nrepl-server code through debugging, other than a dynamic binding of a `sci/print-newline` variable that is always set to true. Could it be that this binding is lost in `sci` on a delayed println execution?

https://github.com/babashka/nbb/blob/8b961191089b364224740f3c61d329db1905dfff/src/nbb/impl/nrepl_server.cljs#L133

```Clojure
   (with-async-bindings
      {sci/ns ns
       sci/file file
       sci/print-length @sci/print-length
       sci/print-newline true}
      ;; we alter-var-root this because the print-fn may go out of scope in case
      ;; of returned delays
      (sci/alter-var-root sci/print-fn (constantly
                                        (fn [s]
                                          (send-fn request {"out" s}))))
      (-> (loop-fn nil)
          (.catch (partial handle-error send-fn request))
          (.finally (fn []
                      (send-fn request {"ns" (str @last-ns)
                                        "status" ["done"]}))))
```
Thanks

**Comment by borkdude** [comment]
Interestingly, `*print-length*` defaults to `false` in CLJS but `true` in planck. I think it has to do with that. Maybe we could just put it to true globally in nREPL and this would solve the problem?

**Comment by ikappaki** [comment]
> Interestingly, `*print-length*` defaults to `false` in CLJS but `true` in planck. I think it has to do with that. Maybe we could just put it to true globally in nREPL and this would solve the problem?

Thanks, this seems to fix the issue.

(Just for reference, as per https://github.com/clojure/clojurescript/blob/e7cdc70d0371a26e07e394ea9cd72d5c43e5e363/src/main/cljs/cljs/core.cljs#L109-L114, `*print-newline*` is

```clojure
(def
  ^{:dynamic true
    :doc "When set to logical false will drop newlines from printing calls.
  This is to work around the implicit newlines emitted by standard JavaScript
  console objects."}
  *print-newline* true)
```
)

Though, out of curiosity, why is the frame with the dynamic `*print-newline*` rebinding in `with-async-bindings` was not referenced by the timeout fn  as expected? Also, does `alter-var` affect the top level root binding of `*print-newline*`, not just one used for that particular nrepl evaluation and thus applies globally rather than for the duration of that nrepl eval?

Thanks

**Comment by borkdude** [comment]
Because timeouts aren't promises, I suppose.

**Comment by ikappaki** [comment]
> Because timeouts aren't promises, I suppose.

Right, I found several references mentioning the lack of dynamic binding effect in async calls in clojurescript
- clojure docs, `binding` example reference to setTimeout https://clojuredocs.org/clojure.core/binding#example-5784550fe4b0bafd3e2a049e

> ;; Beware usage in ClojureScript around asynchronous calls, as the bound
> ;; var's original value will be re-established before the async code executes:

- https://github.com/binaryage/cljs-zones, a library to support custom dynamic bindings in clojurescript.

Though, I can see slight issues changing dynamic vars root in the nrepl server.

For example, in the current example source code posted earlier 

https://github.com/babashka/nbb/blob/8b961191089b364224740f3c61d329db1905dfff/src/nbb/impl/nrepl_server.cljs#L133

https://github.com/babashka/nbb/commit/8b961191089b364224740f3c61d329db1905dfff
```clojure
 (with-async-bindings 

   (with-async-bindings
      {sci/ns ns
       sci/file file
       sci/print-length @sci/print-length
       sci/print-newline true}
      ;; we alter-var-root this because the print-fn may go out of scope in case
      ;; of returned delays
      (sci/alter-var-root sci/print-fn (constantly
                                        (fn [s]
                                          (send-fn request {"out" s}))))
      (-> (loop-fn nil)
          (.catch (partial handle-error send-fn request))
          (.finally (fn []
                      (send-fn request {"ns" (str @last-ns)
                                        "status" ["done"]}))))
```

The `print-fn` fn above is rebound in each eval request. If two clients are connected to the server and a print request within a setTimeout is sent from each whose timeout intervals overlap, then the print output can be send tot he wrong client (because the print-fn destination is reset every time a new request comes). I have tested this to be the case.

Similarly, changing the root binding of `sci/print-newline` globally when the nserver starts (I think this is what you've suggested,), might have a slight annoying effects if the server tries to print out something out of a client request (though I can't think of a scenario where the server tries to print out something of itself outside of a client request).

How challenging would it be to support async dynamic bindings in SCI to cover the `setTimeout` case? I'd have thought SCI has all the information at hand to set the reference frame in `setTimeout` to the one with the dynamic rebounding, but then I am not familiar with the SCI implementation. That would be a very nice bonus feature for nbb/sci, as the current native macro support is.

Thanks

**Comment by borkdude** [comment]
I was suggesting changing it globally in nbb, regardless of REPL

**Comment by ikappaki** [comment]
> I was suggesting changing it globally in nbb, regardless of REPL

This won't work, as per the snippet I posted earlier with regards to the effect of *print-newline* def, its purpose is to account for the extra newline when sending output to the console

https://github.com/clojure/clojurescript/blob/e7cdc70d0371a26e07e394ea9cd72d5c43e5e363/src/main/cljs/cljs/core.cljs#L109-L114

```clojure
(def
  ^{:dynamic true
    :doc "When set to logical false will drop newlines from printing calls.
  This is to work around the implicit newlines emitted by standard JavaScript
  console objects."}
  *print-newline* true)
```

to demonstrate, without any changes
```shell
$ node lib/nbb_main.js 
Welcome to nbb v1.2.174!
user=> 	(println :hi)
:hi
nil
```

with the root binding altered at the top level of `src/nbb/core.cljs` to `(sci/alter-var-root sci/print-newline (constantly true))`, there are extra newlines added to the output

```shell
$ node lib/nbb_main.js 
Welcome to nbb v1.2.174!
user=> (println :hi)
:hi


nil
```

**Comment by borkdude** [comment]
I guess you could just ensure print-newline to be true in your callback then:


```
(binding [*print-newline* true] (println ...))
```

**Comment by borkdude** [comment]
> but when the same thing is run from the REPL, (e.g. by invoking nbb on the command line), it will emit extra newlines

why does it do this?

**Comment by ikappaki** [comment]
> > but when the same thing is run from the REPL, (e.g. by invoking nbb on the command line), it will emit extra newlines
> 
> why does it do this?

Because console.log() and friends implicitly add a newline to the output, and thus we need to suppress the newline coming from println, otherwise there would be two newlines printout. This is done by setting `*print-newline* variable to `false`.

console.log() adds an implicit newline to the output:
```clojure
$ npx nbb
Welcome to nbb v1.1.156!
user=> (do (js/console.log "1") (js/console.log "2"))
1
2
nil
```

`println` output is redirected to the `console` at init; 

https://github.com/babashka/nbb/blob/8b961191089b364224740f3c61d329db1905dfff/src/nbb/core.cljs#L666
``` clojure
(defn init []
  (enable-console-print!)
  (sci/alter-var-root sci/print-fn (constantly *print-fn*))
  (sci/alter-var-root sci/print-err-fn (constantly *print-err-fn*)))
```

since the console already adds an explicit newline, the logic has to make sure that the println newline is suppressed (otherwise we output two newlines to the output). The suppression is controlled by setting the *print-newline*` variable to `false`.

https://github.com/clojure/clojurescript/blob/e7cdc70d0371a26e07e394ea9cd72d5c43e5e363/src/main/cljs/cljs/core.cljs#L193-L205
```clojure
(defn enable-console-print!
  "Set *print-fn* to console.log"
  []
  (set! *print-newline* false)
  (set-print-fn!
    (fn []
      (let [xs (js-arguments)]
        (.apply (.-log js/console) js/console (garray/clone xs)))))
  (set-print-err-fn!
    (fn []
      (let [xs (js-arguments)]
        (.apply (.-error js/console) js/console (garray/clone xs)))))
  nil)
```
