### ISSUE TITLE
Using from node.js - more sandboxing?

### ISSUE THREAD

**Issue by Madd0g** [babashka/nbb#338]
**Is your feature request related to a problem? Please describe.**

1. I'm trying to evaluate multiple scripts one after another with `loadString` and don't want their code to intermix. Is there a way run each `loadString` in a separate "container"?

2. Can I shut-off the globalThis context or manually provide a context myself?

**Describe the solution you'd like**
I want to be able to draw the line between the node.js env better and have better control over how scripts are evaluated.

**Describe alternatives you've considered**
I use `worker_threads` to side-step the problem. I don't like it.

**Additional context**

**Comment by borkdude** [comment]
@Madd0g There are a few things we could do:

On node, instead of worker threads, you can use the `"vm"` builtin module:

1.
```
user=> (def ctx #js {:f (fn [] (vec (range)))})
#'user/ctx
user=> (def context (vm/createContext ctx))
#'user/context
user=> (.runInContext vm "f()" ctx #js {:breakOnSigint true :microtaskMode "afterEvaluate" :displayErrors true})
^C"Error: Script execution was interrupted by `SIGINT`"
```

This allows you to kill long running tasks.

2. To support this, we could expose the SCI interpreter directly inside of nbb. This allows you to execute ClojureScript in a sandboxed fashion.

**Comment by borkdude** [comment]
To experiment right now with 2 you could try babashka, in which SCI is exposed.

**Comment by Madd0g** [comment]
1. when you say vm you mean the node.js vm module, right? I had poor experience trying to use vm with external modules and it had weird issues with ESM modules (not with nbb, just in general).

Do you mean just the loadScript part would be evaluated in the vm? can you give me a quick example of how that might look like in JS?

2. re exposing SCI - I would love to have more control in that area - I actually would probably also find use for the continuous experience where I can add more code to an "environment" (like it works today with loadString) but I want to be able to control when that happens.

Thanks for replying!

**Comment by borkdude** [comment]
@Madd0g 

1. Example, replace the `:f` function with something that uses `loadString`, I guess.
2. Please let me know if exposing SCI would be beneficial after you get a chance to experiment with it then

**Comment by Madd0g** [comment]
1. that is the nbb repl, right? I'm using loadString from a node script. I think I understand what you mean. I'll try to pass loadString as context to vm to see how that works.

2. I'm using node to run nbb + clojure scripts and hoping to have more control on the JS-level, I just started learning clojure. I'll read some babashka code and see if I can understand how babashka uses SCI. It's a big overwhelming to me still.

**Comment by borkdude** [comment]
Let me just expose SCI, I've been meaning to do this anyway.

**Comment by Madd0g** [comment]
thank you.

can you give me a little pointer on how to use it? I don't see any new things exported in the JS api.

**Comment by Madd0g** [comment]
understood, thank you very much!
