### ISSUE TITLE
Could not resolve symbol: `re-matcher`

### ISSUE THREAD

**Issue by avelino** [babashka/nbb#342]
**Is your feature request related to a problem? Please describe.**

Can't find the re-matcher token (from core Clojure) 

```clj
Welcome to nbb v1.2.179!
user=> re-matcher
"#error {:message \"Could not resolve symbol: re-matcher\", :data {:type :sci/error, :line 1, :column 1, :file nil, :phase \"analysis\"}}"
user=>
```

**Describe the solution you'd like**
add `re-matcher`

**Comment by borkdude** [comment]
ClojureScript doesn't have `re-matcher`
