### ISSUE TITLE
Promesa promisify is missing

### ISSUE THREAD

**Issue by chr15m** [babashka/nbb#345]
**version**

v1.2.179

**platform**

Ubuntu 16 Node 16

**problem** / **repro**

```
(Welcome to nbb v1.2.179!
user=> (require '[promesa.core :as p])
user=> p/promisify
"#error {:message \"Could not resolve symbol: p/promisify\", :data {:type :sci/error, :line 1, :column 1, :file nil, :phase \"analysis\"}}"
```

**expected behavior**

Ability to use `promisify`.

**Comment by chr15m** [comment]
> Given a function that accepts a callback as the last argument return other function that returns a promise. Callback is expected to take single parameter (result of a computation).

Basically wraps a callback-accepting function in `js/Promise.` with res passed as the argument.

**Comment by borkdude** [comment]
CI is releasing 1.2.180 where this will be available

**Comment by chr15m** [comment]
Thank you! :pray:
