### ISSUE TITLE
`clj-kondo` doesn't recognize promesa `p/let`

### ISSUE THREAD

**Issue by jianghoy** [babashka/nbb#357]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**
```
nbb v1.2.188
```

**platform**
```
OS: MacOs 14.5 23F79/Sonoma
Editor: VSCode Version: 1.89.1 (Universal)
Plugin: Calva :
Calva version used: v2.0.452
clojure-lsp version used: 2024.04.22-11.58.08-nightly
clj-kondo version used: 2024.03.13
```
**problem**
When I use nbb with clj-kondo with promesa I'm getting error message saying `p/let` variable is not recognized:
<img width="978" alt="Screenshot 2024-06-01 at 10 46 46 PM" src="https://github.com/babashka/nbb/assets/34693285/cbe227b8-11b9-4a60-b68a-7fdb01e9f676">

**repro**
```cljs
(ns script
  (:require [promesa.core :as p]))
(p/let [first-completion (p/-> completion-promise
                                .-choices
                                first)]
        (prn first-completion))
```

**expected behavior**
clj-kondo should recognize this is correct syntax

**Comment by borkdude** [comment]
The promesa library exports configuration for clj-kondo:

https://github.com/funcool/promesa/blob/master/resources/clj-kondo.exports/funcool/promesa/config.edn

You can import this configuration by doing the following:

```
mkdir -p .clj-kondo
clj-kondo --lint "$(clojure -Spath -Sdeps '{:deps {funcool/promesa {:mvn/version "11.0.678"}}}')" --dependencies --copy-configs
```

It looks like you are using Calva. If you put this dependency in `bb.edn` or `deps.edn`, Calva will automatically import this configuration (via clojure-lsp).

Also see https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#exporting-and-importing-configuration
