### ISSUE TITLE
Testing macro messages not showing up in test output

### ISSUE THREAD

**Issue by jaidetree** [babashka/nbb#358]
**version**

1.2.188

**platform**

- Mac OS 14.3.1
- Node 22.2.0

**problem**

When calling `(testing "Extra context")` within `deftest` it should be surfaced in errors. However, with the latest nbb, it's not surfaced at all.

https://github.com/babashka/sci.configs/blob/ffa88d796a3a2fe0a0fce332c6bf56f36b7c5cd7/src/sci/configs/cljs/test.cljs#L374

**repro**

Given code like the following:

```clojure
(deftest basic-test
  (testing "Outer context"
    (testing "inner context"
      (let [x 2]
        (is (= x 3))))))
```

**expected behavior**

A string representation of those testing contexts should be visible in the FAIL reporter function. The code linked above shows the implementation.

**actual**

The output of that looks like the following:

```cljs
FAIL in (basic-test) (:47)
expected: (= x 3)
  actual: (not (= 2 3))
```

**Comment by borkdude** [comment]
> However, with the latest nbb, it's not surfaced at all.

Do you mean it worked with a previous version?

> The output of that looks like the following:

I see code, not output, is that intentional?

**Comment by jaidetree** [comment]
> > However, with the latest nbb, it's not surfaced at all.
> 
> Do you mean it worked with a previous version?

Sorry bad wording on my part. I've only tried it with 1.2.188 so unknown if it worked on previous versions.

> > The output of that looks like the following:
> 
> I see code, not output, is that intentional?

...and that's why I shouldn't create tickets at 3am 😳 anyway updated the ticket with the actual output.

```
FAIL in (async-promise-test) (:47)
expected: (= x 3)
  actual: (not (= 2 3))
```

After the first line, the default reporter should be printing the context str.

**Comment by jaidetree** [comment]
As mentioned in the nbb clojure slack, dug a bit deeper and may have found the cause:

https://github.com/babashka/sci.configs/blob/ffa88d796a3a2fe0a0fce332c6bf56f36b7c5cd7/src/sci/configs/cljs/test.cljs#L301

Note that the `empty-env` function initializes testing-contexts to an empty list.

https://github.com/babashka/sci.configs/blob/ffa88d796a3a2fe0a0fce332c6bf56f36b7c5cd7/src/sci/configs/cljs/test.cljs#L715

The `testing` macro updates the value of the dynamic var `*testing-contexts*`.

https://github.com/babashka/sci.configs/blob/ffa88d796a3a2fe0a0fce332c6bf56f36b7c5cd7/src/sci/configs/cljs/test.cljs#L342

In the default fail reporter, it calls this function but it has no knowledge of the `*testing-contexts*` var, instead just tries to read from the current env which is always an empty list.

Confirmed this with a previous example by overwriting the FAIL reporter to print the value of `*testing-contexts*` instead:

```
FAIL in (basic-test) (:47)
testing contexts (Outer context Inner context)
expected: (= x 3)
  actual: (not (= 2 3))
```

**Comment by borkdude** [comment]
Thanks for the digging, perhaps a PR to fix it?

**Comment by jaidetree** [comment]
Would be honored. That said, not sure the best way to fix this. Maybe `empty-env` should initialize the `:testing-contexts` value to `*testing-contexts*`?

**Comment by borkdude** [comment]
I can take a closer look tomorrow or Thursday or so

**Comment by jaidetree** [comment]
Sounds good. Might give that proposal a shot and see if it works.

**Comment by jaidetree** [comment]
Last note: Looking at the original, https://cljs.github.io/api/cljs.test/testing, seems like the `testing` macro just updates the *current-env* var using the `update-current-env!` function. 

Then we don't need the `*testing-contexts*` dynamic var, and can use the `update-current-env!` function you already ported over.

**Comment by borkdude** [comment]
Thanks for fixing this yourself!
