### ISSUE TITLE
Question: Recommended way for adding libraries written in portable Clojure?

### ISSUE THREAD

**Issue by stelcodes** [babashka/nbb#370]
I'd like to use the Hiccup library [Huff](https://github.com/escherize/huff) with nbb, but I'm not sure the best way to do this. Basically I want to create a static site generator in Typescript that uses nbb as a scripting language so the user can write their page's layout in Hiccup. I could try to reduce Huff to a single file and concat it with the user's script in `loadString`. Is nbb even the right tool here? I'd appreciate any ideas. Thanks!

**Comment by borkdude** [comment]
I'm not sure if huff is SCI-compatible but you can try adding it to `nbb.edn` `:deps` and see if it works?

**Comment by borkdude** [comment]
It seems it crashes on:

```
8: (set! *warn-on-reflection* true)
    ^--- Could not resolve symbol: *warn-on-reflection*
```

so it doesn't seem to be CLJS-compatible?

**Comment by borkdude** [comment]
It does seem to work with bb:

```
$ bb -e "(require '[huff2.core :as h]) (str (h/html [:a]))"
"<a></a>"
```

`borkdude.html` does work in nbb:

```
$ npx nbb -e "(require '[borkdude.html :as h]) (str (h/html [:a]))"
"<a></a>"
```

**Comment by stelcodes** [comment]
Thank you for the tips! I think what I had in mind was a bit ambitious. I'm trying to think of what I should do with my Clojure [static site generator](https://github.com/stelcodes/nuzzle). I want to use Node instead of the JVM to use Remark plugins, but I think the right approach would be to use CLJS and use eval or something.

**Comment by borkdude** [comment]
@stelcodes Note that `eval` doesn't work in CLJS unless you use bootstrap (which yields 8mb of JavaScript) or if you use https://github.com/babashka/sci (which works with advanced CLJS compilation, unlike bootstrap). Nbb is just one example of a CLJS project that uses SCI but there's several others like Clerk, Scittle and Joyride.
