### ISSUE TITLE
Add locking

### ISSUE THREAD

**Issue by gdw2vs** [babashka/nbb#374]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**Is your feature request related to a problem? Please describe.**
I'm working on getting flowstorm working with nbb.  It uses locking a bunch ([example](https://github.com/flow-storm/flow-storm-debugger/blob/a839f8a9919d9a15dd9884da96525d6b2222b045/src-inst/flow_storm/runtime/events.cljc#L14))

**Describe the solution you'd like**
Nbb to implement the [core locking function](https://cljs.github.io/api/cljs.core/locking).  

**Describe alternatives you've considered**
I've considered dropping in the cljs macro definition in, but it appears to _not lock_?

**Comment by borkdude** [comment]
Fixed on master
