### ISSUE TITLE
Support more babashka command line args (--main, --help/help, version)

### ISSUE THREAD

**Issue by kanaka** [babashka/nbb#50]
It would be nice if nbb supported a few of the same basic babashka command line args like `--main`, `--help`, `help`, `version`, `--`, etc.

**Comment by borkdude** [comment]
I agree!

**Comment by cldwalker** [comment]
This would be pretty useful as it would make the tool more user friendly and something I could recommend to more junior folks. For now looks like we can take a look in https://github.com/babashka/nbb/blob/main/src/nbb/impl/main.cljs

**Comment by borkdude** [comment]
Added. Should be available in v0.0.119 in a few minutes.
