### ISSUE TITLE
Consider adding re-frame.core?

### ISSUE THREAD

**Issue by arthurbarroso** [babashka/nbb#79]
**Is your feature request related to a problem? Please describe.**
Are there any plans on supporting all of `goog`'s classes? Like `{:classes {'js goog/global :allow :all}}` in [sci's readme](https://github.com/borkdude/sci#classes). I am trying to use `nbb` with a few things that require access to stuff such as `goog.async.nextTick` and realized [`nbb` doesn't support it](https://github.com/borkdude/nbb/blob/main/src/nbb/core.cljs#L334). I do believe including these classes would be great for people trying to pre-render SPA's using nbb, but am not sure if there are any drawbacks in including all of `goog`'s classes.

**Describe the solution you'd like**
I am not really asking for this to implemented, I'd just like to know if you plan on supporting this. Thank you for your amazing work :)

**Comment by borkdude** [comment]
@arthurbarroso Perhaps you can make a test-repo so we can try to make that code work.

**Comment by arthurbarroso** [comment]
@borkdude I included reagent because I was using `reagent.dom.server` in my project. I've seen you have plans on adding it to nbb though.

**Comment by borkdude** [comment]
reagent.dom.server is already included in the latest bb

**Comment by borkdude** [comment]
For now I think we can close this until more people let us know they want re-frame in nbb.
