### ISSUE TITLE
Make doc etc available in REPL by default

### ISSUE THREAD

**Issue by borkdude** [babashka/nbb#84]
```
user=> (clojure.repl/doc ==)
-------------------------
clojure.core/==
([x] [x y] [x y & more])
  Returns non-nil if nums all have the equivalent
  value, otherwise false. Behavior on non nums is
  undefined.
nil
```

**Comment by borkdude** [comment]
@benjamin-asdf Was this also fixed by your PR? We probably need a test for it.

**Comment by benjamin-asdf** [comment]
```~/repos/clojure/my-reagent-project/src/capy $ my-nbb
user=> (doc + )
(doc + )
-------------------------
clojure.core/+
([] [x] [x y] [x y & more])
  Returns the sum of nums. (+) returns 0.
nil
user=> 
```
can informally confirm that it's fixed yes. In repl and nrepl I think there is also socket repl or something right?

**Comment by borkdude** [comment]
Maybe a test could be to literally call `doc` in the REPL test and check the output.

**Comment by benjamin-asdf** [comment]
Jo when I compile there is `out/nbb_test.js` I think there is a type in `bb.edn` 
` run-tests (shell "node out/nbb_test.js")`
I tried to to add a failing test to `nbb_nrepl_tests.clj` but where does that end up?

**Comment by borkdude** [comment]
@benjamin-asdf Try with `NBB_TESTS=true bb watch`

**Comment by benjamin-asdf** [comment]
NBB_TESTS=true bb watch

should maybe be mentionend in dev.md
@borkdude 
now I made a pr with the test.

**Comment by borkdude** [comment]
@benjamin-asdf Cool! I forgot to mention that the nREPL tests are actually done via babashka. 🤦 
So you can just add the test there, in https://github.com/babashka/nbb/blob/main/script/nbb_nrepl_tests.clj

**Comment by borkdude** [comment]
This is executed when you run `bb run-integration-tests`

**Comment by borkdude** [comment]
Done.
