### ISSUE TITLE
$NODE_PATH should automatically be on the classpath

### ISSUE THREAD

**Issue by chr15m** [babashka/nbb#98]
If `NODE_PATH` is set, Node will assume that as the `node_modules` path when doing `require` and `import`. User expectation is probably that this would be the same for nbb.

Example:

```
NODE_PATH="/home/piku/.piku/envs/sfxrpro/node_modules" nbb somescript.cljs
```

**Comment by borkdude** [comment]
Right now the classpath only affects loading `.cljs` files, not `js` files. `NODE_PATH` should affect loading JS libs. Please provide a more complete standalone repro so I can see that we are talking about the same thing.

**Comment by chr15m** [comment]
Yes, sorry, will do.

**Comment by chr15m** [comment]
Ok, this was an issue with my deployment environment, sorry for the noise.
